
export const metadata = {
  title: 'GanbaDeaf 2.0',
  description: 'Generated by create next app',
}

export default function QAdminLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      {children}
    </>
    // <html lang="uk">
    //   <body>
    //     <main>
    //       {children}
    //     </main>
    //   </body>
    // </html>
  )
}
