import './globals.css'

export const metadata = {
  title: 'GanbaDeaf 2.0',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="uk" className="bg-sky-100 dark:bg-[#012346] text-sky-800 dark:text-blue-200">
      <body className="p-6">
        {children}
      </body>
    </html>
  )
}
